### ISSUE TITLE
Do we have open source code for this paper?

### ISSUE THREAD

**Issue by zxzhijia** [fregu856/papers#1]

**Comment by fregu856** [comment]
Which paper?

**Comment by Mrak1985** [comment]
For the Simple and Scalable Predictive Uncertainty Estimation using Deep Ensembles do they have an open code? Thanks in advance

**Comment by fregu856** [comment]
I don't think so. There is however code for the related paper "Evaluating Scalable Bayesian Deep Learning Methods for Robust Computer Vision": https://github.com/fregu856/evaluating_bdl

**Comment by Mrak1985** [comment]
> I don't think so. There is however code for the related paper "Evaluating Scalable Bayesian Deep Learning Methods for Robust Computer Vision": https://github.com/fregu856/evaluating_bdl

thanks, according to the task of  my individual I have to use this article as the basis - I have in oilfield some oil wells with production rates, so I have to make it work through the method in the article))

**Comment by Mrak1985** [comment]
> I don't think so. There is however code for the related paper "Evaluating Scalable Bayesian Deep Learning Methods for Robust Computer Vision": https://github.com/fregu856/evaluating_bdl

And also if you can compare your solution and there which one is better and easier in realisation? In term of "better" I mean more correctly will solve the uncertain prediction if I understand this right. Thanks in advance

**Comment by Mrak1985** [comment]
> I don't think so. There is however code for the related paper "Evaluating Scalable Bayesian Deep Learning Methods for Robust Computer Vision": https://github.com/fregu856/evaluating_bdl

Here is the code for my question https://paperswithcode.com/paper/simple-and-scalable-predictive-uncertainty
